### ISSUE TITLE
Password hash

### ISSUE THREAD

**Issue by kmbeaulieu** [kmweinrich/SpartanSurveys#7]
Make the password hash and then store the hashed password in the database. This might require purging already created users. 

this applies to sign in and sign up. 

If you plan on working on this, assign yourself.

**Comment by Wrinth** [comment]
I'll work on this issue

**Comment by kmbeaulieu** [comment]
cool :) sam has finished fixing the sign in not doing the password correctly, so you might want to pull what master has so you can edit on the changed activity
